services:
  shortener:
    build: .
    ports:
      - "${API_PORT}:8080"
    volumes:
      - type: bind
        source: ./
        target: /app/
        consistency: delegated
    depends_on:
      postgres:
        condition: service_started
        restart: true
      redis:
        condition: service_started
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - shortener-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - shortener-network

  redis:
    image: redis:6.2
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - shortener-network

networks:
  shortener-network:
    name: shortener-network
    driver: bridge
    external: true
